version: '3'
services:
  postgres:
    image: postgres:11.5-alpine
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
  server:
    build: ./server
    environment:
      - RACK_ENV=development
      - RAILS_ENV=development
    ports:
      - 3000:3000
    command: bundle exec rails server --port 3000 --binding 0.0.0.0
    volumes:
      - ./server:/server
      - bundle:/bundle
    links:
      - postgres
  client:
    build: './client'
    command: sh -c "yarn && yarn serve"
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - server
volumes:
  postgres:
    external: false
  bundle:
